In [19]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

In [6]:
obj = Series([4,7,-5,3])

In [7]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [8]:
obj.values

array([ 4,  7, -5,  3])

In [9]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
obj2 = Series([4,  7, -5,  3],index = ['d','b','a','c'])

In [11]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [12]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [13]:
obj2['a']

-5

In [14]:
obj2['d'] = 6

In [15]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [16]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [17]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [18]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [20]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [21]:
'b' in obj2

True

In [22]:
'e' in obj2

False

In [23]:
sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}

In [24]:
obj3 = Series(sdata)

In [25]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [26]:
states = ['California','Ohio','Oregon','Texas']

In [27]:
obj4 = Series(sdata,index=states)

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [30]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [31]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [32]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [33]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [34]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [35]:
obj4.name = 'population'

In [36]:
obj4.index.name = 'states'

In [37]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [38]:
obj.index = ['Bob','Steve','Jeff','Ryan']

In [39]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [41]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada'],
        'year':[2000,2001,2002,2001,2002],
       'pop':[1.5,1.7,3.6,2.4,2.9]}
frame = DataFrame(data)

In [42]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [44]:
DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [45]:
frame2 = DataFrame(data,columns=['year','state','pop','debt'],
                  index = ['one','two','three','four','five'])

In [46]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [47]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [48]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [49]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [51]:
frame2.ix['three']

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [52]:
frame2['debt'] = 16.5

In [53]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [54]:
frame2['debt'] = np.arange(5)

In [55]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [56]:
val = Series([-1.2,1.5,1.7],index=['two','four','five'])

In [58]:
frame2['debt'] = val

In [59]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4   1.5
five   2002  Nevada  2.9   1.7

In [62]:
frame2['eastern'] = frame2.state == 'Ohio'

In [63]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4   1.5    False
five   2002  Nevada  2.9   1.7    False

In [64]:
del frame2['eastern']

In [65]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [74]:
pop = {'Nevada':{2001:2.4,2002:2.9},
      'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [75]:
frame3 = DataFrame(pop)

In [95]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [77]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [92]:
DataFrame(pop,index=[2001, 2002, 2003],columns=['Nevada','Ohio'])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [97]:
pdata = {'Ohio':frame3['Ohio'][:-1],
        'Nevada':frame3['Nevada'][:2]}

In [98]:
DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [99]:
frame3.index.name = 'year';frame3.columns.name = 'state'

In [100]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [101]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [102]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, 1.5],
       [2002, 'Nevada', 2.9, 1.7]], dtype=object)

In [103]:
obj = Series(range(3),index = ['a','b','c'])

In [104]:
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [106]:
obj.index[1:]

Index(['b', 'c'], dtype='object')

In [107]:
obj.index[1] = 'd'

TypeError: Index does not support mutable operations

In [108]:
index = pd.Index(np.arange(3))

In [110]:
obj2 = Series([1.5,-2.5,0],index = index)

In [111]:
obj2.index is index

True

In [112]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [113]:
'Ohio' in frame3.columns

True

In [114]:
2003 in frame3.index

False

In [115]:
obj = Series([4.5,7.2,-5.3,3.6],index = ['d','b','a','c'])

In [116]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [117]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [118]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [119]:
obj.reindex(['a','b','c','d','e'],fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [120]:
obj3 = Series(['blue','purple','yellow'],index = [0,2,4])

In [121]:
obj3.reindex(range(6),method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [122]:
frame = DataFrame(np.arange(9).reshape((3,3)),index = ['a','c','d'],
                 columns=['Ohio','Texas','California'])

In [130]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [124]:
frame2 =frame.reindex(['a','b','c','d'])

In [125]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [126]:
states = ['Texas','Utah','California']

In [134]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [138]:
frame.reindex(index=['a','b','c','d'],columns=states).ffill()

Texas  Utah  California
a    1.0   NaN         2.0
b    1.0   NaN         2.0
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [139]:
frame.ix[['a','b','c','d'],states]

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [140]:
obj = Series(np.arange(5),index=['a','b','c','d','e'])

In [141]:
new_obj = obj.drop('c')

In [142]:
new_obj

a    0
b    1
d    3
e    4
dtype: int64

In [144]:
obj.drop(['d','c'])

a    0
b    1
e    4
dtype: int64

In [145]:
data = DataFrame(np.arange(16).reshape((4,4)),
                index=['Ohio','Colorado','Utah','New York'],
                columns=['one','two','three','four'] )

In [146]:
data.drop(['Ohio','Colorado'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [147]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [148]:
data.drop(['two','four'],axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [149]:
obj = Series(np.arange(4),index=['a','b','c','d'])

In [150]:
obj['b']

1

In [152]:
obj[1]

1

In [153]:
obj[2:4]

c    2
d    3
dtype: int64

In [155]:
obj[['b','a','d']]

b    1
a    0
d    3
dtype: int64

In [156]:
obj[[1,3]]

b    1
d    3
dtype: int64

In [157]:
obj[obj<2]

a    0
b    1
dtype: int64

In [158]:
obj['b':'c']

b    1
c    2
dtype: int64

In [159]:
obj['b':'c'] = 5

In [160]:
obj

a    0
b    5
c    5
d    3
dtype: int64

In [162]:
data = DataFrame(np.arange(16).reshape((4,4)), index=['Ohio','Colorado','Utah','New York'],
                columns=['one','two','three','four'] )

In [163]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [164]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [165]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [166]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [167]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [168]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [169]:
data[data<5]=0

In [170]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [173]:
data.ix['Colorado',['two','three']]

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


two      5
three    6
Name: Colorado, dtype: int64

In [174]:
data.ix[['Colorado','Utah'],[3,0,1]]

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


four  one  two
Colorado     7    0    5
Utah        11    8    9

In [175]:
data.ix[2]

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [176]:
data.ix[data.three>5,:3]

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [177]:
s1 = Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])

In [179]:
s2 = Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])

In [180]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [181]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [182]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [185]:
df1 = pd.DataFrame(np.arange(9).reshape((3,3)),columns=list('bcd'),index=['Ohio','Texas','Colorado'])

In [190]:
df2 = pd.DataFrame(np.arange(12).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [191]:
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [192]:
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [193]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [199]:
df1 = DataFrame(np.arange(12).reshape((3,4)),columns=list('abcd'))

In [200]:
df2 = DataFrame(np.arange(20).reshape((4,5)),columns=list('abcde'))

In [201]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [202]:
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [203]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [204]:
df1.add(df2,fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [205]:
df1.reindex(columns=df2.columns,fill_value=0)

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

In [206]:
arr = np.arange(12).reshape(3,4)

In [207]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [208]:
arr[0]

array([0, 1, 2, 3])

In [209]:
arr-arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [210]:
frame = DataFrame(np.arange(12).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [211]:
series = frame.ix[0]

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


In [212]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [213]:
series

b    0
d    1
e    2
Name: Utah, dtype: int64

In [214]:
frame - series

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [216]:
series2 = Series(range(3),index = ['b','e','f'])

In [217]:
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [218]:
series3 = frame['d']

In [219]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [220]:
series3

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int64

In [221]:
frame.sub(series3,axis=0)

b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

In [222]:
frame = DataFrame(np.random.randn(4,3),columns=list('bde'),index = ['Utah','Ohio','Texas','Oregon'])

In [223]:
frame

b         d         e
Utah    1.926626 -0.912755  1.335945
Ohio   -0.726613 -1.096876  0.449276
Texas  -0.751388  1.027454  0.450255
Oregon -0.271840 -0.155301 -0.156434

In [224]:
np.abs(frame)

b         d         e
Utah    1.926626  0.912755  1.335945
Ohio    0.726613  1.096876  0.449276
Texas   0.751388  1.027454  0.450255
Oregon  0.271840  0.155301  0.156434

In [225]:
f = lambda x:x.max()-x.min()

In [226]:
frame.apply(f)

b    2.678014
d    2.124330
e    1.492379
dtype: float64

In [227]:
frame.apply(f,axis=1)

Utah      2.839380
Ohio      1.546153
Texas     1.778842
Oregon    0.116539
dtype: float64

In [230]:
def f(x):
    return Series([x.min(),x.max()],index=['min','max'])

In [231]:
frame.apply(f)

b         d         e
min -0.751388 -1.096876 -0.156434
max  1.926626  1.027454  1.335945

In [232]:
format = lambda x:'%.2f'%x

In [233]:
frame.applymap(format)

b      d      e
Utah     1.93  -0.91   1.34
Ohio    -0.73  -1.10   0.45
Texas   -0.75   1.03   0.45
Oregon  -0.27  -0.16  -0.16

In [234]:
frame['e'].map(format)

Utah       1.34
Ohio       0.45
Texas      0.45
Oregon    -0.16
Name: e, dtype: object

In [235]:
obj = Series(range(4),index=['d','a','b','c'])

In [236]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [237]:
frame = DataFrame(np.arange(8).reshape(2,4),index=['three','one'],
                 columns=['d','a','b','c'])

In [238]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [240]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [243]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [275]:
import pandas as pd
obj = pd.Series([4,7,-3,-2])

In [277]:
obj.sort_values()

2   -3
3   -2
0    4
1    7
dtype: int64

In [249]:
obj = Series([4,np.nan,7,np.nan,-3,2])

In [278]:
obj.sort_values()

2   -3
3   -2
0    4
1    7
dtype: int64

In [252]:
frame = DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [253]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [254]:
frame.sort_index(by='b')

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  """Entry point for launching an IPython kernel.


b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [255]:
frame.sort_index(by=['a','b'])

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  """Entry point for launching an IPython kernel.


b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [256]:
obj = Series([7,-5,7,4,2,0,4])

In [257]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [258]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [259]:
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [261]:
frame = DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})

In [262]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [263]:
frame.rank(axis=1)

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [264]:
obj = Series(range(5),index=['a','a','b','b','c'])

In [265]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [266]:
obj.index.is_unique

False

In [267]:
obj['a']

a    0
a    1
dtype: int64

In [268]:
obj['c']

4

In [269]:
df = DataFrame(np.random.randn(4,3),index=['a','a','b','b'])

In [270]:
df

0         1         2
a -0.391833  0.503747  1.553358
a -0.722424  1.189730 -0.087797
b -1.929932 -1.520128  0.181823
b -0.749137 -0.647961 -0.932128

In [271]:
df.ix['b']

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


0         1         2
b -1.929932 -1.520128  0.181823
b -0.749137 -0.647961 -0.932128

In [280]:
df = pd.DataFrame([[1.4,np.nan],[7.1,4.5],[np.nan,np.nan],[0.75,-1.3]],index=['a','b','c','d'],columns=['one','two'])

In [281]:
df

one  two
a  1.40  NaN
b  7.10  4.5
c   NaN  NaN
d  0.75 -1.3

In [282]:
df.sum()

one    9.25
two    3.20
dtype: float64

In [283]:
df.sum(axis=1)

a     1.40
b    11.60
c     0.00
d    -0.55
dtype: float64

In [284]:
df.mean(axis=1,skipna=False)

a      NaN
b    5.800
c      NaN
d   -0.275
dtype: float64

In [285]:
df.idxmax()

one    b
two    b
dtype: object

In [286]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50  4.5
c   NaN  NaN
d  9.25  3.2

In [287]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333  1.600000
std    3.493685  4.101219
min    0.750000 -1.300000
25%    1.075000  0.150000
50%    1.400000  1.600000
75%    4.250000  3.050000
max    7.100000  4.500000

In [288]:
obj = Series(['a','b','c','d']*4)

In [289]:
obj.describe()

count     16
unique     4
top        c
freq       4
dtype: object

In [299]:
import pandas_datareader.data as web
all_data = {ticker:web.get_data_yahoo(ticker)
             for ticker in ['AAPL','IBM','MSFT','GOOG']}


In [307]:
price = DataFrame({tic:data['Adj Close']
                  for tic,data in all_data.items()})
volume = DataFrame({tic:data['Volume']
                   for tic,data in all_data.items()})

In [300]:
returns = price.pct_change()

In [301]:
returns.tail()

AAPL  IBM  MSFT
Date                       
1999-12-31   NaN  NaN   NaN

In [302]:
returns.MSFT.corr(returns.IBM)

nan

In [303]:
returns.MSFT.cov(returns.IBM)

nan

In [304]:
returns.corr()

AAPL  IBM  MSFT
AAPL   NaN  NaN   NaN
IBM    NaN  NaN   NaN
MSFT   NaN  NaN   NaN

In [305]:
returns.corrwith(returns.IBM)

AAPL   NaN
IBM    NaN
MSFT   NaN
dtype: float64

In [308]:
returns.corrwith(volume)

AAPL   NaN
GOOG   NaN
IBM    NaN
MSFT   NaN
dtype: float64

In [309]:
obj = Series(['c','a','d','a','a','b','b','c','c'])

In [312]:
uniques = obj.unique()

In [313]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [315]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [319]:
pd.value_counts(obj.values,sort=False)

d    1
b    2
a    3
c    3
dtype: int64

In [320]:
mask = obj.isin(['b','c'])

In [321]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [322]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [323]:
data = DataFrame({'Qu1':[1,3,4,3,4],
                  'Qu2':[2,3,1,2,3],
                  'Qu3':[1,5,2,4,4]})

In [326]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [327]:
result = data.apply(pd.value_counts).fillna(0)

In [329]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [330]:
string_data = Series(['aardvark','artichoke',np.nan,'avocado'])

In [331]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [332]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [333]:
string_data[0] = None

In [334]:
from numpy import nan as NA

In [335]:
data = Series([1,NA,3.5,NA,7])

In [336]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [338]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64